version: "3.8"

services: 
  #################################################
  #
  # Smartcontract
  #
  #################################################
  crosschain-lp-smartcontracts:
    build:
      context: ./smartcontracts
    container_name: "crosschain-lp-smartcontracts"
    volumes:
      - type: bind
        source: ./smartcontracts
        target: /home/node/app
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file:
      - ./smartcontracts/.env
volumes: 
  db-data:
networks:
  net:
