version: "3.8"

services: 
  #################################################
  #
  # Website services
  #
  #################################################
  website:
    build:
      context: ./website
    container_name: "website"
    volumes:
      - type: bind
        source: ./website
        target: /home/node/app
      - /home/node/app/node_modules
    networks:
      - net
    # entrypoint: sh
    # command: '-c "sleep 1d"'
    command: ["npm", "run", "start"]
    env_file:
      - ./website/.env
    ports: 
      - 443:443
  #################################################
  #
  # Smartcontract
  #
  #################################################
  smartcontract:
    build:
      context: ./smartcontract
    container_name: "smartcontract"
    volumes:
      - type: bind
        source: ./smartcontract
        target: /home/node/app
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file:
      - ./Smartcontract/.env

  #################################################
  #
  # ORACLE Services
  #
  #################################################
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    env_file: 
      - oracle/postgres.env
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - net

  chainlink:
    build: ./oracle
    env_file:
      - ./oracle/chainlink.env
    command: local node -p /chainlink/.password -a /chainlink/.api
    container_name: "chainlink"
    restart: on-failure
    ports: 
      - 6688:6688
    links:
      - postgres
      - target-gas-price
    depends_on: 
      - postgres
    volumes:
      - type: bind
        source: ./oracle/chainlink_data
        target: /chainlink
    networks:
      - net
  target-gas-price:
    build: ./oracle/adapters/target-gas-price/.
    env_file:
      - ./oracle/adapters/target-gas-price/.env
    container_name: "target-gas-price"
    volumes:
      - type: bind
        source: ./oracle/adapters/target-gas-price
        target: /home/node/app
      - /home/node/app/node_modules
    ports:
      - 8080:8080
    networks:
      - net
volumes: 
  db-data:
networks:
  net:
